name: Terraform Setup

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      tf-cloud-token:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      aws-access-key-id:
        required: true
        type: string
      aws-secret-access-key:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: "Configure Terraform credentials"
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ inputs.tf-cloud-token }}"
              }
            }
          }
          EOF

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: echo "Terraform plan failed"

      - name: Terraform Apply
        id: apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Set output
        if: steps.apply.outcome == 'success'
        run: echo "::set-output name=apply_status::success"
